#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

0_0  # Python >= 3.6 is required

import secrets
import sys

import wormhole.cli.cli as cli

def main():
    n = 100000 + secrets.randbelow(900000)
    code = secrets.token_urlsafe(16)
    sys.argv[0:1] = ['wormhole', 'send', '--code', f'{n}-{code}']
    return cli.wormhole()

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
